name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
      - master
    tags:
      - v*
    paths-ignore:
      - '.*'
      - '.*/workflows/**'
      - 'README*'
      - '**/README*'
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - '.*'
      - '.*/workflows/**'
      - 'README*'
      - '**/README*'

env:
  DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
  DOCKER_PLATFORMS: ${{ github.event_name == 'pull_request' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Image Tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "DOCKER_IMAGE_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ]; then
            if [[ "${{ github.ref }}" == refs/tags/* ]]; then
              echo "DOCKER_IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            else
              echo "DOCKER_IMAGE_TAG=latest" >> $GITHUB_ENV
            fi
          fi

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest
          load: ${{ github.event_name != 'push' }}
          push: ${{ github.event_name == 'push' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max